### PR TITLE
[lipstick] Remove connectivityMonitor from qml api. Contributes to JB#59897

### PR DESCRIPTION
**Pull request by pvuorela**
Such a thing doesn't belong to homescreen services and for what I can tell it hasn't ever even be used for anything(?).

For starters just remove the context property now. Removing the rest can be handled later.

### CODE REVIEW

**Comment by pvuorela** [comment]
Actually looking more closely, seems like the whole thing is pretty much no-op these days.  From the updated commit message:

    The QML api doesn't appear ever used.
    
    For the rest, the vpn-updown.service seems removed from
    nemo-qml-plugin-systemsettings in 2018, commit 3ab5248a, JB#41460
    -> the updown should have been a no-op for a while now.

**Comment by LaakkonenJussi** [comment]
Couldn't build this. Took a fresh upstream repo and took this PR and used latest 64bit SDK:
```
g++ -c -pipe -Wfatal-errors -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DLIPSTICK_BUILD_LIBRARY -DVERSION=\"0.36.25+36.20230118114506.6398788c\" -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 -DQT_COMPOSITOR_QUICK -DHAVE_CONTENTACTION -DQT_NO_DEBUG -DQT_COMPOSITOR_LIB -DQT_COMPOSITOR_WAYLAND_GL -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_SENSORS_LIB -DQT_CORE_LIB -I. -Iutilities -Itouchscreen -Icomponents -Ixtools -I3rdparty -Idevicestate -Icompositor -Icompositor/alienmanager -isystem /usr/include/qt5/QtCompositor/5.6.3 -isystem /usr/include/qt5/QtCompositor/5.6.3/QtCompositor -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCompositor -isystem /usr/include/qt5/QtQuick/5.6.3 -isystem /usr/include/qt5/QtQuick/5.6.3/QtQuick -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui/5.6.3 -isystem /usr/include/qt5/QtGui/5.6.3/QtGui -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml/5.6.3 -isystem /usr/include/qt5/QtQml/5.6.3/QtQml -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore/5.6.3 -isystem /usr/include/qt5/QtCore/5.6.3/QtCore -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtSensors -isystem /usr/include/qt5/QtCore -I.moc -isystem /usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -isystem /usr/include/keepalive -isystem /usr/include/resource/qt5 -isystem /usr/include/resource -isystem /usr/include/mlite5 -isystem /usr/include/mce-qt5 -isystem /usr/include/ngf-qt5 -isystem /usr/include/systemsettings -isystem /usr/include/profiled -isystem /usr/include/libsailfishkeyprovider -isystem /usr/include/connman-qt5 -isystem /usr/include/usb-moded-qt5 -isystem /usr/include/sailfishusermanager -isystem /usr/include/contentaction5 -I/usr/share/qt5/mkspecs/linux-g++ -o .obj/windowpixmapitem.o compositor/windowpixmapitem.cpp
make[1]: *** No rule to make target '3rdparty/dbus-gmain/dbus-gmain.c', needed by '.obj/dbus-gmain.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....

**Comment by LaakkonenJussi** [comment]
> Couldn't build this. Took a fresh upstream repo and took this PR and used latest 64bit SDK:
> 
> ```
> g++ -c -pipe -Wfatal-errors -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DLIPSTICK_BUILD_LIBRARY -DVERSION=\"0.36.25+36.20230118114506.6398788c\" -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 -DQT_COMPOSITOR_QUICK -DHAVE_CONTENTACTION -DQT_NO_DEBUG -DQT_COMPOSITOR_LIB -DQT_COMPOSITOR_WAYLAND_GL -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_SENSORS_LIB -DQT_CORE_LIB -I. -Iutilities -Itouchscreen -Icomponents -Ixtools -I3rdparty -Idevicestate -Icompositor -Icompositor/alienmanager -isystem /usr/include/qt5/QtCompositor/5.6.3 -isystem /usr/include/qt5/QtCompositor/5.6.3/QtCompositor -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCompositor -isystem /usr/include/qt5/QtQuick/5.6.3 -isystem /usr/include/qt5/QtQuick/5.6.3/QtQuick -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui/5.6.3 -isystem /usr/include/qt5/QtGui/5.6.3/QtGui -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml/5.6.3 -isystem /usr/include/qt5/QtQml/5.6.3/QtQml -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore/5.6.3 -isystem /usr/include/qt5/QtCore/5.6.3/QtCore -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtSensors -isystem /usr/include/qt5/QtCore -I.moc -isystem /usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -isystem /usr/include/keepalive -isystem /usr/include/resource/qt5 -isystem /usr/include/resource -isystem /usr/include/mlite5 -isystem /usr/include/mce-qt5 -isystem /usr/include/ngf-qt5 -isystem /usr/include/systemsettings -isystem /usr/include/profiled -isystem /usr/include/libsailfishkeyprovider -isystem /usr/include/connman-qt5 -isystem /usr/include/usb-moded-qt5 -isystem /usr/include/sailfishusermanager -isystem /usr/include/contentaction5 -I/usr/share/qt5/mkspecs/linux-g++ -o .obj/windowpixmapitem.o compositor/windowpixmapitem.cpp
> make[1]: *** No rule to make target '3rdparty/dbus-gmain/dbus-gmain.c', needed by '.obj/dbus-gmain.o'.  Stop.
> make[1]: *** Waiting for unfinished jobs....
> ```

Oh wait, this happens also with master..

**Comment by LaakkonenJussi** [comment]
> > Couldn't build this. Took a fresh upstream repo and took this PR and used latest 64bit SDK:
> > ```
> > g++ -c -pipe -Wfatal-errors -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DLIPSTICK_BUILD_LIBRARY -DVERSION=\"0.36.25+36.20230118114506.6398788c\" -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 -DQT_COMPOSITOR_QUICK -DHAVE_CONTENTACTION -DQT_NO_DEBUG -DQT_COMPOSITOR_LIB -DQT_COMPOSITOR_WAYLAND_GL -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_SENSORS_LIB -DQT_CORE_LIB -I. -Iutilities -Itouchscreen -Icomponents -Ixtools -I3rdparty -Idevicestate -Icompositor -Icompositor/alienmanager -isystem /usr/include/qt5/QtCompositor/5.6.3 -isystem /usr/include/qt5/QtCompositor/5.6.3/QtCompositor -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCompositor -isystem /usr/include/qt5/QtQuick/5.6.3 -isystem /usr/include/qt5/QtQuick/5.6.3/QtQuick -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui/5.6.3 -isystem /usr/include/qt5/QtGui/5.6.3/QtGui -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml/5.6.3 -isystem /usr/include/qt5/QtQml/5.6.3/QtQml -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore/5.6.3 -isystem /usr/include/qt5/QtCore/5.6.3/QtCore -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtSensors -isystem /usr/include/qt5/QtCore -I.moc -isystem /usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -isystem /usr/include/keepalive -isystem /usr/include/resource/qt5 -isystem /usr/include/resource -isystem /usr/include/mlite5 -isystem /usr/include/mce-qt5 -isystem /usr/include/ngf-qt5 -isystem /usr/include/systemsettings -isystem /usr/include/profiled -isystem /usr/include/libsailfishkeyprovider -isystem /usr/include/connman-qt5 -isystem /usr/include/usb-moded-qt5 -isystem /usr/include/sailfishusermanager -isystem /usr/include/contentaction5 -I/usr/share/qt5/mkspecs/linux-g++ -o .obj/windowpixmapitem.o compositor/windowpixmapitem.cpp
> > make[1]: *** No rule to make target '3rdparty/dbus-gmain/dbus-gmain.c', needed by '.obj/dbus-gmain.o'.  Stop.
> > make[1]: *** Waiting for unfinished jobs....
> > ```
> 
> Oh wait, this happens also with master..

Ah, this had submodules..

**Review by LaakkonenJussi — APPROVED** [review]
LGTM and seems to do no harm on the device. Existing functionality does seem to work in regards to network.

**Pull request merged**
