### PR TITLE
Add Discord to androidnotificationpriorities

### PR DESCRIPTION
**Pull request by JacekJagosz**
Discord is one of the most popular chat apps right now, this makes the notifications work as they should be.

### CODE REVIEW

**Comment by pvuorela** [comment]
The explicit package overrides for android apps has been a thing we've wanted to get rid of and instead just handle good the notification properties the android apps set. With commit 3035cb81359 this was some months ago restricted to the old android 4 handling used on some old devices (jolla c, xperia x) which is not getting notification improvements anymore.

I'm not totally objecting in adding this but with above in mind wondering if it's too useful anymore.

**Comment by JacekJagosz** [comment]
Is that feature already exists in 4.4 and Android 10? I did that only because discord wasn't showing an icon, not making sounds and vibrating. So it seemed like adding it improved things.
If in next release this will be introduced then I agree this pull can be dropped, or maybe accepted for X users. But it is weird it seemed like this file still does something on my 10 III

**Comment by pvuorela** [comment]
For Xperia 10 III this change will have no effect on releases after 4.4.

**Comment by JacekJagosz** [comment]
So do you think this can get merged for the older devices that still make use of this file, and Discord is probably one of the most common Android apps to use?
Or should I close this pull request?

**Comment by pvuorela** [comment]
I can merge this as the change itself looks good. I'll skip tagging and integrating fully yet as the change also shouldn't have much impact.

**Review by pvuorela — APPROVED** [review]

**Pull request merged**
